export const KEYWORDS = [
  "Software Engineer",
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "AI Engineer",
  "ML Engineer",
];

export const GREENHOUSE_API_BASE = "https://boards-api.greenhouse.io/v1/boards";
export const ASHBY_API_BASE = "https://api.ashbyhq.com/posting-api/job-board";

export type PortalProvider = "greenhouse" | "ashby";

export interface Portal {
  name: string;
  provider: PortalProvider;
  boardToken: string;
}

export function getGreenhouseApiUrl(boardToken: string): string {
  return `${GREENHOUSE_API_BASE}/${boardToken}/jobs`;
}

export function getAshbyApiUrl(boardToken: string): string {
  return `${ASHBY_API_BASE}/${boardToken}`;
}

const GREENHOUSE_COMPANIES = [
  { name: "Anthropic", provider: "greenhouse", boardToken: "anthropic" },
  { name: "Figma", provider: "greenhouse", boardToken: "figma" },
  { name: "Stripe", provider: "greenhouse", boardToken: "stripe" },
  { name: "Airbnb", provider: "greenhouse", boardToken: "airbnb" },
  { name: "Airtable", provider: "greenhouse", boardToken: "airtable" },
  { name: "Attentive", provider: "greenhouse", boardToken: "attentive" },
  { name: "Betterment", provider: "greenhouse", boardToken: "betterment" },
  { name: "Checkr", provider: "greenhouse", boardToken: "checkr" },
  { name: "ClickHouse", provider: "greenhouse", boardToken: "clickhouse" },
  { name: "Cockroach Labs", provider: "greenhouse", boardToken: "cockroachlabs" },
  { name: "Contentful", provider: "greenhouse", boardToken: "contentful" },
  { name: "Datadog", provider: "greenhouse", boardToken: "datadog" },
  { name: "dbt Labs", provider: "greenhouse", boardToken: "dbtlabsinc" },
  { name: "Instacart", provider: "greenhouse", boardToken: "instacart" },
  { name: "Discord", provider: "greenhouse", boardToken: "discord" },
  { name: "Coinbase", provider: "greenhouse", boardToken: "coinbase" },
  { name: "Gusto", provider: "greenhouse", boardToken: "gusto" },
  { name: "LaunchDarkly", provider: "greenhouse", boardToken: "launchdarkly" },
  { name: "Lob", provider: "greenhouse", boardToken: "lob" },
  { name: "PagerDuty", provider: "greenhouse", boardToken: "pagerduty" },
  { name: "PitchBook", provider: "greenhouse", boardToken: "pitchbookdata" },
  { name: "Roblox", provider: "greenhouse", boardToken: "roblox" },
  { name: "Dropbox", provider: "greenhouse", boardToken: "dropbox" },
  { name: "Webflow", provider: "greenhouse", boardToken: "webflow" },
  { name: "Yext", provider: "greenhouse", boardToken: "yext" },
  { name: "Oscar", provider: "greenhouse", boardToken: "oscar" },
  { name: "Okta", provider: "greenhouse", boardToken: "okta" },
  { name: "Arkana Laboratories", provider: "greenhouse", boardToken: "arkanalaboratories" },
  { name: "Easthampton", provider: "greenhouse", boardToken: "easthampton" },
  { name: "Carvana", provider: "greenhouse", boardToken: "carvana" },
  { name: "Truckstop", provider: "greenhouse", boardToken: "truckstop" },
  { name: "Abnormal Security", provider: "greenhouse", boardToken: "abnormalsecurity" },
  { name: "Akuna Capital", provider: "greenhouse", boardToken: "akunacapital" },
  { name: "Bitmovin", provider: "greenhouse", boardToken: "bitmovin" },
  { name: "Brex", provider: "greenhouse", boardToken: "brex" },
  { name: "Broadriver", provider: "greenhouse", boardToken: "broadriver" },
  { name: "Burr", provider: "greenhouse", boardToken: "burr" },
  { name: "Businessolver", provider: "greenhouse", boardToken: "businessolver" },
  { name: "CaptiveAire", provider: "greenhouse", boardToken: "captiveaire" },
  { name: "Challenge Manufacturing", provider: "greenhouse", boardToken: "challengemfgcompany" },
  { name: "Clever", provider: "greenhouse", boardToken: "clever" },
  { name: "Connecteam", provider: "greenhouse", boardToken: "connecteam" },
  { name: "Coupang", provider: "greenhouse", boardToken: "coupang" },
  { name: "Cribl", provider: "greenhouse", boardToken: "cribl" },
  { name: "Culture Biosciences", provider: "greenhouse", boardToken: "culturebiosciences" },
  { name: "Databricks", provider: "greenhouse", boardToken: "databricks" },
  { name: "DigiCert", provider: "greenhouse", boardToken: "digicert" },
  { name: "DISCO", provider: "greenhouse", boardToken: "disco" },
  { name: "Ensono", provider: "greenhouse", boardToken: "ensono" },
  { name: "Epic Tails Veterinary Clinic", provider: "greenhouse", boardToken: "epictailsveterinaryclinic" },
  { name: "FanDuel", provider: "greenhouse", boardToken: "fanduel" },
  { name: "Fieldwire", provider: "greenhouse", boardToken: "fieldwire" },
  { name: "Finanzcheck", provider: "greenhouse", boardToken: "finanzcheck" },
  { name: "Frazier Deeter", provider: "greenhouse", boardToken: "frazierdeeter" },
  { name: "Hitachi Vantara", provider: "greenhouse", boardToken: "hitachivantaracorporation" },
  { name: "IXL Learning", provider: "greenhouse", boardToken: "ixllearning" },
  { name: "Jump Trading", provider: "greenhouse", boardToken: "jumptrading" },
  { name: "Keen Footwear", provider: "greenhouse", boardToken: "keenfootwear" },
  { name: "Liaison International", provider: "greenhouse", boardToken: "liaisoninternational" },
  { name: "Lightricks", provider: "greenhouse", boardToken: "lightricks" },
  { name: "Mark43", provider: "greenhouse", boardToken: "mark43" },
  { name: "Merchants Fleet", provider: "greenhouse", boardToken: "merchantsfleetmanagement" },
  { name: "Mind Foundry", provider: "greenhouse", boardToken: "mindfoundry" },
  { name: "MongoDB", provider: "greenhouse", boardToken: "mongodb" },
  { name: "MSG Entertainment", provider: "greenhouse", boardToken: "msgentertainmentholdingsllc" },
  { name: "Neighbors Bank", provider: "greenhouse", boardToken: "neighborsbank" },
  { name: "Oakhurst", provider: "greenhouse", boardToken: "oakhurst" },
  { name: "Octagon", provider: "greenhouse", boardToken: "octagon" },
  { name: "PebblePost", provider: "greenhouse", boardToken: "pebblepost" },
  { name: "Pindrop", provider: "greenhouse", boardToken: "pindropsecurity" },
  { name: "PMC", provider: "greenhouse", boardToken: "pmc" },
  { name: "Relay Network", provider: "greenhouse", boardToken: "relaynetwork" },
  { name: "Remote TCX", provider: "greenhouse", boardToken: "remotetcx" },
  { name: "Ripple", provider: "greenhouse", boardToken: "ripple" },
  { name: "Salt Security", provider: "greenhouse", boardToken: "saltsecurity" },
  { name: "SoFi", provider: "greenhouse", boardToken: "sofi" },
  { name: "SupportLogic", provider: "greenhouse", boardToken: "supportlogic" },
  { name: "Swoogo", provider: "greenhouse", boardToken: "swoogo" },
  { name: "Tetra", provider: "greenhouse", boardToken: "tetra" },
  { name: "Tigera", provider: "greenhouse", boardToken: "tigera" },
  { name: "Toss", provider: "greenhouse", boardToken: "tosscareers" },
  { name: "Unity", provider: "greenhouse", boardToken: "unity3d" },
  { name: "URPT", provider: "greenhouse", boardToken: "urpt" },
  { name: "Ventura Travel", provider: "greenhouse", boardToken: "venturatravel" },
  { name: "Veracyte", provider: "greenhouse", boardToken: "veracyte" },
  { name: "ZeroCater", provider: "greenhouse", boardToken: "zerocater" },
  { name: "Zeta Charter Schools", provider: "greenhouse", boardToken: "zetacharterschools" },
] satisfies Portal[];

const ASHBY_COMPANIES = [
  { name: "Ema", provider: "ashby", boardToken: "ema" },
  { name: "Harvey", provider: "ashby", boardToken: "harvey" },
  { name: "Sesame", provider: "ashby", boardToken: "sesame" },
  { name: "PermitFlow", provider: "ashby", boardToken: "permitflow" },
  { name: "Hopper", provider: "ashby", boardToken: "hopper" },
  { name: "Casium", provider: "ashby", boardToken: "casium" },
  { name: "Onebrief", provider: "ashby", boardToken: "onebrief" },
  { name: "Abridge", provider: "ashby", boardToken: "abridge" },
  { name: "Claylabs", provider: "ashby", boardToken: "claylabs" },
  { name: "SKELAR", provider: "ashby", boardToken: "SKELAR" },
  { name: "Aios", provider: "ashby", boardToken: "Aios" },
  { name: "Ridealso", provider: "ashby", boardToken: "Ridealso" },
  { name: "Ambience Healthcare", provider: "ashby", boardToken: "ambiencehealthcare" },
  { name: "9am", provider: "ashby", boardToken: "join9am" },
  { name: "Pulley", provider: "ashby", boardToken: "withpulley" },
  { name: "EverAI", provider: "ashby", boardToken: "everai" },
  { name: "Neo Financial", provider: "ashby", boardToken: "neofinancial" },
  { name: "Public Cloud Group", provider: "ashby", boardToken: "publiccloudgroup" },
  { name: "Polymarket", provider: "ashby", boardToken: "polymarket" },
  { name: "Solace", provider: "ashby", boardToken: "solace" },
  { name: "Cohere", provider: "ashby", boardToken: "cohere" },
  { name: "Replit", provider: "ashby", boardToken: "replit" },
  { name: "Notion", provider: "ashby", boardToken: "notion" },
  { name: "Ramp", provider: "ashby", boardToken: "ramp" },
  { name: "Vanta", provider: "ashby", boardToken: "vanta" },
  { name: "Linear", provider: "ashby", boardToken: "linear" },
  { name: "Valon", provider: "ashby", boardToken: "valon" },
  { name: "Notable", provider: "ashby", boardToken: "notable" },
  { name: "Coder", provider: "ashby", boardToken: "coder" },
  { name: "Help Scout", provider: "ashby", boardToken: "helpscout" },
  { name: "Sardine", provider: "ashby", boardToken: "sardine" },
  { name: "Pylon", provider: "ashby", boardToken: "pylon" },
  { name: "Savvy", provider: "ashby", boardToken: "savvy" },
  { name: "Plaud", provider: "ashby", boardToken: "Plaud" },
  { name: "1Password", provider: "ashby", boardToken: "1password" },
  { name: "Teamworks", provider: "ashby", boardToken: "teamworks" },
  { name: "Clipboard", provider: "ashby", boardToken: "clipboard" },
  { name: "Blockworks", provider: "ashby", boardToken: "blockworks" },
  { name: "Juicebox", provider: "ashby", boardToken: "Juicebox" },
  { name: "Aspora", provider: "ashby", boardToken: "Aspora" },
  { name: "Hilberts", provider: "ashby", boardToken: "hilberts" },
  { name: "Skimmer", provider: "ashby", boardToken: "skimmer" },
  { name: "Wealthsimple", provider: "ashby", boardToken: "wealthsimple" },
  { name: "Talent Safari", provider: "ashby", boardToken: "talentsafari" },
  { name: "OpusClip", provider: "ashby", boardToken: "opusclip" },
  { name: "Rwazi", provider: "ashby", boardToken: "rwazi" },
  { name: "FloatMe", provider: "ashby", boardToken: "FloatMe" },
  { name: "Zencastr", provider: "ashby", boardToken: "zencastr" },
  { name: "Prompt", provider: "ashby", boardToken: "prompt" },
  { name: "Maybern", provider: "ashby", boardToken: "maybern" },
  { name: "H Company", provider: "ashby", boardToken: "hcompany" },
  { name: "Kalshi", provider: "ashby", boardToken: "kalshi" },
  { name: "Distyl", provider: "ashby", boardToken: "Distyl" },
  { name: "Capi Money", provider: "ashby", boardToken: "capimoney" },
  { name: "NetBox Labs", provider: "ashby", boardToken: "netboxlabs" },
  { name: "Bevel", provider: "ashby", boardToken: "bevel" },
  { name: "Pebl", provider: "ashby", boardToken: "pebl" },
  { name: "OneApp", provider: "ashby", boardToken: "oneapp" },
  { name: "Reality Defender", provider: "ashby", boardToken: "realitydefender" },
  { name: "Comity", provider: "ashby", boardToken: "comity" },
  { name: "Anagram", provider: "ashby", boardToken: "anagram" },
  { name: "Vitalize", provider: "ashby", boardToken: "vitalize" },
  { name: "Whippy", provider: "ashby", boardToken: "whippy" },
  { name: "Hawk", provider: "ashby", boardToken: "hawk" },
  { name: "Vetcove", provider: "ashby", boardToken: "Vetcove" },
  { name: "Render", provider: "ashby", boardToken: "render" },
  { name: "Playson", provider: "ashby", boardToken: "playson" },
  { name: "Vibe", provider: "ashby", boardToken: "vibe" },
  { name: "Pave Bank", provider: "ashby", boardToken: "pavebank" },
  { name: "MyEdSpace", provider: "ashby", boardToken: "myedspacecareers" },
  { name: "Middesk", provider: "ashby", boardToken: "middesk" },
  { name: "Dave", provider: "ashby", boardToken: "dave" },
  { name: "Colonist", provider: "ashby", boardToken: "colonist" },
  { name: "Additive AI", provider: "ashby", boardToken: "additiveai" },
  { name: "WeTravel", provider: "ashby", boardToken: "wetravel" },
  { name: "Phia", provider: "ashby", boardToken: "phia" },
  { name: "Common Room", provider: "ashby", boardToken: "commonroom" },
  { name: "Mechanize", provider: "ashby", boardToken: "mechanize" },
  { name: "Mangomint", provider: "ashby", boardToken: "mangomint" },
  { name: "Heron Data", provider: "ashby", boardToken: "herondata" },
  { name: "Hello Hera", provider: "ashby", boardToken: "hellohera" },
  { name: "Coworker", provider: "ashby", boardToken: "Coworker" },
  { name: "Auctor", provider: "ashby", boardToken: "auctor" },
  { name: "Centari", provider: "ashby", boardToken: "centari" },
  { name: "OpenRouter", provider: "ashby", boardToken: "openrouter" },
  { name: "Vooma", provider: "ashby", boardToken: "vooma" },
  { name: "Chai Discovery", provider: "ashby", boardToken: "chaidiscovery" },
  { name: "Double", provider: "ashby", boardToken: "double" },
  { name: "Jump", provider: "ashby", boardToken: "jump" },
  { name: "Opal", provider: "ashby", boardToken: "opal" },
  { name: "Cluely", provider: "ashby", boardToken: "cluely" },
  { name: "Raiku", provider: "ashby", boardToken: "raiku" },
  { name: "Bliro", provider: "ashby", boardToken: "bliro" },
  { name: "Synquery", provider: "ashby", boardToken: "synquery" },
  { name: "Aescape", provider: "ashby", boardToken: "aescape" },
  { name: "Asimov", provider: "ashby", boardToken: "asimov" },
  { name: "Dryft", provider: "ashby", boardToken: "dryft" },
  { name: "KPR", provider: "ashby", boardToken: "KPR" },
  { name: "Uplane", provider: "ashby", boardToken: "uplane" },
  { name: "Open Home Foundation", provider: "ashby", boardToken: "openhomefoundation" },
  { name: "Metadao", provider: "ashby", boardToken: "metadao" },
  { name: "Continua", provider: "ashby", boardToken: "continua" },
  { name: "Oumi", provider: "ashby", boardToken: "oumi" },
  { name: "Topos Bio", provider: "ashby", boardToken: "toposbio" },
  { name: "Infracost", provider: "ashby", boardToken: "infracost" },
  { name: "Woflow", provider: "ashby", boardToken: "woflow" },
  { name: "Clarium", provider: "ashby", boardToken: "clarium" },
  { name: "Zircuit", provider: "ashby", boardToken: "Zircuit" },
  { name: "Team Eigen", provider: "ashby", boardToken: "teameigen" },
  { name: "ETHGlobal", provider: "ashby", boardToken: "ethglobal" },
  { name: "Reliable Robotics", provider: "ashby", boardToken: "reliable-robotics" },
  { name: "Hinge Health", provider: "ashby", boardToken: "hinge-health" },
  { name: "Runway ML", provider: "ashby", boardToken: "runway-ml" },
  { name: "Hadrian Automation", provider: "ashby", boardToken: "hadrian-automation" },
  { name: "Kraken", provider: "ashby", boardToken: "kraken.com" },
  { name: "Liquid AI", provider: "ashby", boardToken: "liquid-ai" },
  { name: "Sprinter Health", provider: "ashby", boardToken: "sprinter-health" },
  { name: "Ambient AI", provider: "ashby", boardToken: "ambient.ai" },
  { name: "Tempo XYZ", provider: "ashby", boardToken: "tempo-xyz" },
  { name: "Sully AI", provider: "ashby", boardToken: "sully-ai" },
  { name: "Douro Labs", provider: "ashby", boardToken: "dourolabs.xyz" },
  { name: "Wealth.com", provider: "ashby", boardToken: "wealth-com" },
  { name: "Strala AI", provider: "ashby", boardToken: "strala-ai" },
  { name: "Primer", provider: "ashby", boardToken: "primer.io" },
  { name: "Monad Foundation", provider: "ashby", boardToken: "monad.foundation" },
  { name: "Topline Pro", provider: "ashby", boardToken: "topline-pro" },
  { name: "Jimdo", provider: "ashby", boardToken: "jimdo.com" },
  { name: "9 Mothers", provider: "ashby", boardToken: "9-mothers" },
  { name: "Nexus", provider: "ashby", boardToken: "nexus.xyz" },
  { name: "Onyx Bio", provider: "ashby", boardToken: "onyx-bio" },
  { name: "Fonzi AI", provider: "ashby", boardToken: "fonzi-ai" },
  { name: "Fauna Robotics", provider: "ashby", boardToken: "fauna-robotics" },
  { name: "Volka", provider: "ashby", boardToken: "volka" },
  { name: "Perplexity", provider: "ashby", boardToken: "perplexity" },
] satisfies Portal[];

export const PORTALS: Portal[] = [...GREENHOUSE_COMPANIES, ...ASHBY_COMPANIES];
